global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: [ '172.19.0.2:15692' ]

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]
